### ISSUE TITLE
Quick Start documantation wrong sample code

### ISSUE THREAD

**Issue by ykaragol** [dschmidt/ember-cli-deploy-cp#6]
The document hosted at https://github.com/dschmidt/ember-cli-deploy-cp has a "Quick Start" section.
In this section, the sample code below the "Place the following configuration into config/deploy.js" is wrong, there should be an equal character just after ENV.cp.
ENV.cp = {
  destDir: '/srv/www/htdocs/'
}

**Comment by dschmidt** [comment]
Good catch. Thanks!
